title: Hung3a8 Blog
email: hung3a8@gmail.com
description: >-
  I hate fixing bugs.
domain: hung3a8.github.io
url: https://hung3a8.github.io
github_username:  hung3a8

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
